services:
    pact-broker:
        container_name: pact-broker
        image: pactfoundation/pact-broker:latest-multi
        ports:
            - 9292:9292
        depends_on:
            - database
        environment:
            PACT_BROKER_DATABASE_USERNAME: pactbroker
            PACT_BROKER_DATABASE_PASSWORD: pactbroker
            PACT_BROKER_DATABASE_HOST: database
            PACT_BROKER_DATABASE_NAME: pact
    database:
        image: "postgres:14"
        container_name: "super-database"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql

    monitoring:
        image: "prom/prometheus:v2.30.3"
        container_name: "super-visor"
        ports:
            - 9090:9090
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    zookeeper:
        image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
        container_name: "zookeeper"
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs

    kafka:
        image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
        container_name: "kafka"
        command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

